{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend.serviceAccountName" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.serviceAccount.accountId }}:role/{{ .Values.serviceAccount.roleName }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
